# https://taskfile.dev
version: "3"

vars:
  PYTHON: uv run python
  PYTEST: uv run pytest
  RUFF: uv run ruff
  BLACK: uv run black
  MYPY: uv run mypy

tasks:
  # ========================
  # Setup & Installation
  # ========================
  default:
    desc: Show available tasks
    cmds:
      - task --list

  install:uv:
    desc: Install UV package manager (Linux/macOS only)
    platforms: [linux, darwin]
    cmds:
      - curl -LsSf https://astral.sh/uv/install.sh | sh
      - echo ""
      - echo "✓ UV installed! Restart your terminal or run 'source ~/.bashrc'"

  install:uv:help:
    desc: Show UV installation instructions for all platforms
    silent: true
    cmds:
      - |
        echo "UV Installation Instructions"
        echo "============================"
        echo ""
        echo "Linux/macOS:"
        echo "  curl -LsSf https://astral.sh/uv/install.sh | sh"
        echo ""
        echo "macOS (Homebrew):"
        echo "  brew install uv"
        echo ""
        echo "Windows (winget):"
        echo "  winget install -e --id astral-sh.uv"
        echo ""
        echo "Windows (PowerShell):"
        echo "  irm https://astral.sh/uv/install.ps1 | iex"
        echo ""
        echo "More info: https://docs.astral.sh/uv/getting-started/installation/"

  check:uv:
    desc: Check if UV is installed
    silent: true
    cmds:
      - |
        if ! command -v uv &> /dev/null; then
          echo "❌ UV is not installed."
          echo "  Run 'task install:uv:help' for installation instructions."
          exit 1
        fi
        echo "✓ UV is installed: $(uv --version)"

  install:
    desc: Install all dependencies
    deps: ["check:uv"]
    cmds:
      - uv sync --all-extras

  setup:
    desc: Full project setup (install + pre-commit)
    deps: ["check:uv"]
    cmds:
      - task: install
      - uv run pre-commit install
      - echo "✓ Setup complete! Run 'task' to see available commands."

  # ========================
  # Code Quality
  # ========================
  check:
    desc: Run all code quality checks (lint, format, types)
    cmds:
      - "{{.RUFF}} check src tests"
      - "{{.BLACK}} --check src tests"
      - "{{.MYPY}} src"

  fix:
    desc: Auto-fix code issues (lint + format)
    cmds:
      - "{{.RUFF}} check --fix src tests"
      - "{{.RUFF}} format src tests"
      - "{{.BLACK}} src tests"

  # ========================
  # Testing
  # ========================
  test:
    desc: Run tests
    cmds:
      - "{{.PYTEST}}"

  test:cov:
    desc: Run tests with coverage
    cmds:
      - "{{.PYTEST}} --cov=src --cov-report=term-missing --cov-report=html"

  test:watch:
    desc: Run tests in watch mode (requires pytest-watch)
    cmds:
      - uv run pytest-watch

  # ========================
  # Pre-commit
  # ========================
  pre-commit:
    desc: Run pre-commit on all files
    cmds:
      - uv run pre-commit run --all-files

  pre-commit:install:
    desc: Install pre-commit hooks
    cmds:
      - uv run pre-commit install

  # ========================
  # Utilities
  # ========================
  clean:
    desc: Clean up generated files
    cmds:
      - rm -rf .pytest_cache
      - rm -rf .mypy_cache
      - rm -rf .ruff_cache
      - rm -rf htmlcov
      - rm -rf .coverage
      - rm -rf dist
      - rm -rf build
      - rm -rf *.egg-info
      - find . -type d -name "__pycache__" -exec rm -rf {} + 2>/dev/null || true
